language: php

php:
  - 5.4
  - 5.5
  - 5.6

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

  - sh -c "composer require 'cakephp/cakephp-codesniffer:*'"
  - phpenv rehash

  - phpenv rehash
  - set +H
  - cp phpunit.xml.dist phpunit.xml

script:

notifications:
  email: false
